/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Service.SVChiacathi;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import mode.Sinhvien;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author dell
 */
public class Outputkehoachthi extends javax.swing.JFrame {

    ButtonGroup groupbutton = new ButtonGroup();
    static List<Sinhvien> _lstSV = new ArrayList<>();
    List<String> ngaythi = new ArrayList<>();
    DefaultTableModel tbmode2 = new DefaultTableModel();
    DefaultTableModel tbmode1 = new DefaultTableModel();
    DefaultTableModel tbmode3 = new DefaultTableModel();
    DefaultTableModel tbmode4 = new DefaultTableModel();
    DefaultTableModel tbmode5 = new DefaultTableModel();
    

    /**
     * Creates new form Outputkehoachthi
     */
    public Outputkehoachthi() {
        initComponents();
    }
    
    private void loadtb(List<Sinhvien> lst, int sosv){
        tbmode1 = (DefaultTableModel) tb1.getModel();
        tbmode1.setRowCount(0);
        tbmode2 = (DefaultTableModel) tb2.getModel();
        tbmode2.setRowCount(0);
        tbmode3 = (DefaultTableModel) tb3.getModel();
        tbmode3.setRowCount(0);
        int i = 1;
        for (Sinhvien x : lst) {
            if (i<=sosv) {
                tbmode1.addRow(new Object[]{x.getTensv(),x.getNgaythi()});
            }
            if (i>sosv&&i<=sosv*2) {
                tbmode2.addRow(new Object[]{x.getTensv(),x.getNgaythi()});
            }
            if (i>sosv*2&&i<sosv*3) {
                tbmode3.addRow(new Object[]{x.getTensv(),x.getNgaythi()});
            }
            i++;
        }
        
    }

    void groupbuton() {
        groupbutton.add(rdthucong);
        groupbutton.add(rdTudong);
    }

    public static void getlstSV(List<Sinhvien> lst) {
        _lstSV = lst;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rdthucong = new javax.swing.JRadioButton();
        rdTudong = new javax.swing.JRadioButton();
        txtsobuoithi = new javax.swing.JTextField();
        lblbuoithithu = new javax.swing.JLabel();
        tab = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb1 = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        tb2 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tb3 = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        tb4 = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        tb5 = new javax.swing.JTable();
        btntet = new javax.swing.JButton();
        datechooser = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
<<<<<<< HEAD
        btnok = new javax.swing.JButton();
        txtsosv = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
=======
        btntet1 = new javax.swing.JButton();
        txtsobuoithi1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
>>>>>>> 03435cfd68c981b8aed8dab741fc877dee1196c6

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rdthucong.setText("Chia buoi thu cong");
        getContentPane().add(rdthucong, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, -1, -1));

        rdTudong.setText("Chia buoi tu dong");
        getContentPane().add(rdTudong, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, -1, -1));

        txtsobuoithi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsobuoithiActionPerformed(evt);
            }
        });
        getContentPane().add(txtsobuoithi, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 60, 40, -1));

        lblbuoithithu.setText("Chon cac ngay thi");
        getContentPane().add(lblbuoithithu, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 90, -1, -1));

        tb1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tb1);

        tab.addTab("Ngay thu nhat", jScrollPane1);

        tb2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tb2);

        tab.addTab("Ngay thu 3", jScrollPane3);

        tb3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tb3);

        tab.addTab("Ngay thu 2", jScrollPane2);

        tb4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(tb4);

        tab.addTab("Ngay thu 2", jScrollPane4);

        tb5.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane5.setViewportView(tb5);

        tab.addTab("Ngay thu 2", jScrollPane5);

        getContentPane().add(tab, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 910, 340));

        btntet.setText("RESET");
        btntet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntetActionPerformed(evt);
            }
        });
        getContentPane().add(btntet, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 90, -1, -1));

        datechooser.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                datechooserAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
<<<<<<< HEAD
        datechooser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                datechooserMouseClicked(evt);
            }
        });
        getContentPane().add(datechooser, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 90, 150, -1));

        jLabel5.setText("SO buoi thi");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 60, -1, -1));

        btnok.setText("OK");
        btnok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnokActionPerformed(evt);
            }
        });
        getContentPane().add(btnok, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 50, 60, -1));

        txtsosv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsosvActionPerformed(evt);
            }
        });
        getContentPane().add(txtsosv, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 60, 40, -1));

        jLabel6.setText("So SV moi buoi");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 60, -1, -1));
=======
        getContentPane().add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 90, 150, -1));

        jLabel5.setText("SO buoi thi");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 60, -1, -1));
>>>>>>> 03435cfd68c981b8aed8dab741fc877dee1196c6

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
<<<<<<< HEAD
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 50, -1, -1));
=======
        getContentPane().add(btntet1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 50, 60, -1));

        txtsobuoithi1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsobuoithi1ActionPerformed(evt);
            }
        });
        getContentPane().add(txtsobuoithi1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 60, 40, -1));

        jLabel6.setText("So SV moi buoi");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 60, -1, -1));
>>>>>>> 03435cfd68c981b8aed8dab741fc877dee1196c6

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btntetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntetActionPerformed
        // TODO add your handling code here:
//        int a = Integer.parseInt(txtsobuoithi.getText());
//        switch (a) {
//            case 1:
//                tab.removeAll();
//                tab.addTab("buoi nay", tb1);
//                break;
//        }
//        tab.addTab(txtsobuoithi.getText(), tb1);
        JOptionPane.showMessageDialog(rootPane, datechooser.getDateFormatString());
        int a = Integer.parseInt(txtsobuoithi.getText());
        switch(a){
            case 1:
                tab.removeAll();
                tab.addTab("buoi nay", tb1);
                break;
        }
        tab.addTab(txtsobuoithi.getText(), tb1);
    }//GEN-LAST:event_btntetActionPerformed

    private void datechooserAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_datechooserAncestorAdded
        // TODO add your handling code here:

    }//GEN-LAST:event_datechooserAncestorAdded

    private void txtsobuoithiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsobuoithiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsobuoithiActionPerformed

    private void btnokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnokActionPerformed
        // TODO add your handling code here:
        int sobuoi;
        int index = 1;
        try {
            sobuoi = Integer.parseInt(txtsobuoithi.getText());
        } catch (Exception e) {
            sobuoi = 0;
        }
//        try {
//            sosv = Integer.parseInt(txtsosv.getText());
//        } catch (Exception e) {
//            sosv = 0;
//        }
        if (ngaythi.size() == sobuoi) {
            return;
        }
        ngaythi.add(SVChiacathi.formatdate(datechooser.getDate()));
        
    }//GEN-LAST:event_btnokActionPerformed

    private void txtsosvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsosvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsosvActionPerformed

    private void datechooserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_datechooserMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_datechooserMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        List<Sinhvien> lst =  SVChiacathi.lstSVfinish(SVChiacathi.fake(), ngaythi, 3, 15);
        loadtb(lst,15);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtsobuoithi1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsobuoithi1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsobuoithi1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Outputkehoachthi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Outputkehoachthi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Outputkehoachthi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Outputkehoachthi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Outputkehoachthi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnok;
    private javax.swing.JButton btntet;
    private com.toedter.calendar.JDateChooser datechooser;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JLabel lblbuoithithu;
    private javax.swing.JRadioButton rdTudong;
    private javax.swing.JRadioButton rdthucong;
    private javax.swing.JTabbedPane tab;
    private javax.swing.JTable tb1;
    private javax.swing.JTable tb2;
    private javax.swing.JTable tb3;
    private javax.swing.JTable tb4;
    private javax.swing.JTable tb5;
    private javax.swing.JTextField txtsobuoithi;
<<<<<<< HEAD
    private javax.swing.JTextField txtsosv;
=======
    private javax.swing.JTextField txtsobuoithi1;
>>>>>>> 03435cfd68c981b8aed8dab741fc877dee1196c6
    // End of variables declaration//GEN-END:variables
}
